let meses = new Array('Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago','Set', 'Out', 'Nov', 'Dez')
let semana = new Array('Dom', 'Seg', 'Ter', 'Qua', 'qui', 'Sex', 'Sab', 'Dom',)
let agora = new data
let saida = document.getElementById('saida')
let dia = agora.getDate()
let mes = agora.getMonth()
let ano = agora.getFullYear()
let sem = agora.getDay()
let hora = agora.getHours()
let min = agora.getMinutes()
let seg = agora.getSeconds()
saida.innerHTML = `<p>Dia: <mark>${dia}</mark></p>`
saida.innerHTML += `<p>Mês: <mark>${meses[mes]}</mark></p>`
saida.innerHTML += `<p>Ano: <mark>${ano}</mark></p>`
saida.innerHTML += `<p>Dia: <mark>${semana[sem]}</mark></p>`
saida.innerHTML += `<p>Hora: <mark>${hora}</mark></p>`
saida.innerHTML += `<p>Minuto: <mark>${min}</mark></p>`
saida.innerHTML += `<p>Segundo: <mark>${seg}</mark></p>`